// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_sync_flutter_libs/objectbox_sync_flutter_libs.dart';

import 'models/meditation_record.dart';
import 'repositories/cache/chant_cache_repository.dart';
import 'repositories/cache/watch_cache_repository.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 6949642974877216044),
    name: 'MeditationRecord',
    lastPropertyId: const obx_int.IdUid(4, 6288952347734034313),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4300879540340383976),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6447807786091323714),
        name: 'meditationStartTime',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 9062785543077691015),
        name: 'meditationDuration',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6288952347734034313),
        name: 'meditationNote',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 4219723709065808279),
    name: 'ChantCache',
    lastPropertyId: const obx_int.IdUid(3, 284770491881884666),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6566735793837556905),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 284770491881884666),
        name: 'chantJsonPath',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 4490759528521803291),
    name: 'WatchCache',
    lastPropertyId: const obx_int.IdUid(5, 2123220754852059554),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5953587341173696777),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8191091518484814759),
        name: 'cachedMeditationWatchStartTime',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2589957026637105673),
        name: 'elapsed',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 2123220754852059554),
        name: 'note',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(4, 4490759528521803291),
    lastIndexId: const obx_int.IdUid(0, 0),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [1929920104100698143],
    retiredIndexUids: const [],
    retiredPropertyUids: const [
      6616827391750416634,
      8484852593009153436,
      5403878557590192250,
      1178143364910113680,
      4144645317619590000,
    ],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    MeditationRecord: obx_int.EntityDefinition<MeditationRecord>(
      model: _entities[0],
      toOneRelations: (MeditationRecord object) => [],
      toManyRelations: (MeditationRecord object) => {},
      getId: (MeditationRecord object) => object.id,
      setId: (MeditationRecord object, int id) {
        object.id = id;
      },
      objectToFB: (MeditationRecord object, fb.Builder fbb) {
        final meditationNoteOffset = fbb.writeString(object.meditationNote);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.meditationStartTime.millisecondsSinceEpoch);
        fbb.addInt64(2, object.meditationDuration);
        fbb.addOffset(3, meditationNoteOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final meditationStartTimeParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0),
        );
        final meditationDurationParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final meditationNoteParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final object = MeditationRecord(
          meditationStartTime: meditationStartTimeParam,
          meditationDuration: meditationDurationParam,
          meditationNote: meditationNoteParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    ChantCache: obx_int.EntityDefinition<ChantCache>(
      model: _entities[1],
      toOneRelations: (ChantCache object) => [],
      toManyRelations: (ChantCache object) => {},
      getId: (ChantCache object) => object.id,
      setId: (ChantCache object, int id) {
        object.id = id;
      },
      objectToFB: (ChantCache object, fb.Builder fbb) {
        final chantJsonPathOffset = fbb.writeString(object.chantJsonPath);
        fbb.startTable(4);
        fbb.addInt64(0, object.id);
        fbb.addOffset(2, chantJsonPathOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final chantJsonPathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final object = ChantCache(chantJsonPath: chantJsonPathParam)
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    WatchCache: obx_int.EntityDefinition<WatchCache>(
      model: _entities[2],
      toOneRelations: (WatchCache object) => [],
      toManyRelations: (WatchCache object) => {},
      getId: (WatchCache object) => object.id,
      setId: (WatchCache object, int id) {
        object.id = id;
      },
      objectToFB: (WatchCache object, fb.Builder fbb) {
        final noteOffset = fbb.writeString(object.note);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addInt64(
          1,
          object.cachedMeditationWatchStartTime?.millisecondsSinceEpoch,
        );
        fbb.addInt64(3, object.elapsed);
        fbb.addOffset(4, noteOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final cachedMeditationWatchStartTimeValue = const fb.Int64Reader()
            .vTableGetNullable(buffer, rootOffset, 6);
        final cachedMeditationWatchStartTimeParam =
            cachedMeditationWatchStartTimeValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(
                cachedMeditationWatchStartTimeValue,
              );
        final elapsedParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final noteParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final object = WatchCache(
          cachedMeditationWatchStartTime: cachedMeditationWatchStartTimeParam,
          elapsed: elapsedParam,
          note: noteParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [MeditationRecord] entity fields to define ObjectBox queries.
class MeditationRecord_ {
  /// See [MeditationRecord.id].
  static final id = obx.QueryIntegerProperty<MeditationRecord>(
    _entities[0].properties[0],
  );

  /// See [MeditationRecord.meditationStartTime].
  static final meditationStartTime = obx.QueryDateProperty<MeditationRecord>(
    _entities[0].properties[1],
  );

  /// See [MeditationRecord.meditationDuration].
  static final meditationDuration = obx.QueryIntegerProperty<MeditationRecord>(
    _entities[0].properties[2],
  );

  /// See [MeditationRecord.meditationNote].
  static final meditationNote = obx.QueryStringProperty<MeditationRecord>(
    _entities[0].properties[3],
  );
}

/// [ChantCache] entity fields to define ObjectBox queries.
class ChantCache_ {
  /// See [ChantCache.id].
  static final id = obx.QueryIntegerProperty<ChantCache>(
    _entities[1].properties[0],
  );

  /// See [ChantCache.chantJsonPath].
  static final chantJsonPath = obx.QueryStringProperty<ChantCache>(
    _entities[1].properties[1],
  );
}

/// [WatchCache] entity fields to define ObjectBox queries.
class WatchCache_ {
  /// See [WatchCache.id].
  static final id = obx.QueryIntegerProperty<WatchCache>(
    _entities[2].properties[0],
  );

  /// See [WatchCache.cachedMeditationWatchStartTime].
  static final cachedMeditationWatchStartTime =
      obx.QueryDateProperty<WatchCache>(_entities[2].properties[1]);

  /// See [WatchCache.elapsed].
  static final elapsed = obx.QueryIntegerProperty<WatchCache>(
    _entities[2].properties[2],
  );

  /// See [WatchCache.note].
  static final note = obx.QueryStringProperty<WatchCache>(
    _entities[2].properties[3],
  );
}
